version: '7'

services:
  bdcontainer:
    container_name: bdcontainer
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
       -- MYSQL_ROOT_PASSWORD=pass2023
    volume:
      - volume_mysql:/var/liv/mysql
    networks:
      - rede_webacademy

bdquicontainer:
  container_name: bdguicontainer
  image: phpmyadmin:latest
  ports:
    - 8080:8080
  environment:
    - PMA_HOST=BDCONTAINER
    - PMA_PORT=3306
    - PMA_USER=ROOT
    - PMA_PASSWOR=pass2023
  depends_on:
    - bdcontainer
  networks:
    - rede_webacademy


networks:
  rede_webacademy:
    driver: bridge

volumes:
  volume_mysql