services:
  backend:
    build: ./back
    container_name: backend
    image: back-node
    ports:
      - "4000:4000"
    networks:
      - rede-node

  frontend:
    build: ./front
    container_name: frontend
    image: front-node
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rede-node

networks:
  rede-node: